### ISSUE TITLE
Возможная утечка памяти в ReallocGraph

### ISSUE THREAD

**Issue by AmdirSword** [otr1v/GRAPH#2]
Добрый день!
Возможно, в `ReallocGraph` есть утечка памяти для массива `edges`.
Я в этой функции вижу следующие события:
1. Выделение памяти для временного хранилища дуг.
2. Копирование дуг во временное хранилище.
3. Выделение памяти под новое хранилище дуг. При этом затираются старые указатели на выделенную память без их освобождения.
4. Копирование дуг из временного хранилища в новое.
Таким образом, я не наблюдаю никакого освобождения старой памяти, она остаётся висеть до конца работы программы. И когда-нибудь память в куче закончится...

Полагаю, тут имеет смысл сделать следующий код:
```
int old_numnodes = graph->numnodes;
graph->numnodes *= 2;

// Reallocate subarrays
for (int idx = 0; idx < old_numnodes; idx++)
{
    graph->edges[idx] = (bool*) realloc(graph->edges[idx], sizeof(bool) * graph->numnodes);
    CHECK_ERR(graph->edges[idx] == NULL, "NOT ENOUGH MEMORY");
}

// Reallocate main array
graph->edges = (bool**) realloc(graph->edges, sizeof(bool*) * graph->numnodes);
CHECK_ERR(graph->edges == NULL, "NOT ENOUGH MEMORY");

// Allocate new subarrays
for (int idx = old_numnodes; idx < graph->numnodes; idx++)
{
    graph->edges[idx] = (bool*) calloc(sizeof(bool), graph->numnodes);
    CHECK_ERR(graph->edges[idx] == NULL, "NOT ENOUGH MEMORY");
}
```

**Comment by AmdirSword** [comment]
Ой, тут ещё и доступ к невыделенной памяти есть в существующей версии...
Я тут поменял в makefile строку компиляции tests вот так:
```
g++ tests.cpp funcgraph.cpp -o tests -g -Wall -Wextra -Wpedantic -Werror -fsanitize=address
```
Уже на компиляции возникла проблема в `main`. Поправил main следующим образом:
```
    struct Graph* graph = NULL;

    struct Test* test = (struct Test*) malloc(sizeof(struct Test));
    FILE* base = NULL;
    Tests(graph, test, base);

    return 0;
```

Ещё я поправил данные для тестов вот так (по сути, просто продублировал для воспроизведения проблемы):
```
2
ADD_NODE 1
ADD_NODE 2
ADD_NODE 3
ADD_NODE 4
ADD_NODE 5
ADD_NODE 6
ADD_NODE 7
ADD_NODE 7
ADD_EDGE 1 2
ADD_EDGE 2 4
ADD_EDGE 4 5
ADD_EDGE 5 2
ADD_EDGE 1 3
ADD_EDGE 3 6
ADD_EDGE 6 7
ADD_EDGE 4 6
END
1 2 4 5 6 7 3
ADD_NODE 1
ADD_NODE 2
ADD_NODE 3
ADD_NODE 4
ADD_NODE 5
ADD_NODE 6
ADD_NODE 7
ADD_NODE 7
ADD_EDGE 1 2
ADD_EDGE 2 4
ADD_EDGE 4 5
ADD_EDGE 5 2
ADD_EDGE 1 3
ADD_EDGE 3 6
ADD_EDGE 6 7
ADD_EDGE 4 6
END
1 2 4 5 6 7 3
```

И по итогу получил ошибку от санитайзера:
```
Node with num 7 is already exist
found loop 5 -> 2
found loop 3 -> 6
=================================================================
==32522==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000edf8 at pc 0x40206d bp 0x7ffc3253fd20 sp 0x7ffc3253fd18
READ of size 1 at 0x60200000edf8 thread T0
    #0 0x40206c in ReallocGraph(Graph*) /home/shamparov_v/Downloads/GRAPH-master/GRAPH-master/funcgraph.cpp:134
    #1 0x40150f in AddNode(Graph*, _IO_FILE*) /home/shamparov_v/Downloads/GRAPH-master/GRAPH-master/funcgraph.cpp:52
    #2 0x403194 in ReadCommands(Graph*, _IO_FILE*, _IO_FILE*) /home/shamparov_v/Downloads/GRAPH-master/GRAPH-master/funcgraph.cpp:263
    #3 0x403720 in Tests(Graph*, Test*, _IO_FILE*) /home/shamparov_v/Downloads/GRAPH-master/GRAPH-master/funcgraph.cpp:323
    #4 0x400d72 in main /home/shamparov_v/Downloads/GRAPH-master/GRAPH-master/tests.cpp:9
    #5 0x7fb143d1ab44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)
    #6 0x400c68 (/home/shamparov_v/Downloads/GRAPH-master/GRAPH-master/tests+0x400c68)

0x60200000edf8 is located 0 bytes to the right of 8-byte region [0x60200000edf0,0x60200000edf8)
allocated by thread T0 here:
    #0 0x7fb144918885 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x54885)
    #1 0x401b10 in ReallocGraph(Graph*) /home/shamparov_v/Downloads/GRAPH-master/GRAPH-master/funcgraph.cpp:109
    #2 0x40150f in AddNode(Graph*, _IO_FILE*) /home/shamparov_v/Downloads/GRAPH-master/GRAPH-master/funcgraph.cpp:52
    #3 0x403194 in ReadCommands(Graph*, _IO_FILE*, _IO_FILE*) /home/shamparov_v/Downloads/GRAPH-master/GRAPH-master/funcgraph.cpp:263
    #4 0x403720 in Tests(Graph*, Test*, _IO_FILE*) /home/shamparov_v/Downloads/GRAPH-master/GRAPH-master/funcgraph.cpp:323
    #5 0x400d72 in main /home/shamparov_v/Downloads/GRAPH-master/GRAPH-master/tests.cpp:9
    #6 0x7fb143d1ab44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/shamparov_v/Downloads/GRAPH-master/GRAPH-master/funcgraph.cpp:134 ReallocGraph(Graph*)
Shadow bytes around the buggy address:
  0x0c047fff9d60: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
  0x0c047fff9d70: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
  0x0c047fff9d80: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
  0x0c047fff9d90: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
  0x0c047fff9da0: fa fa 00 fa fa fa 00 fa fa fa 00 fa fa fa 00 fa
=>0x0c047fff9db0: fa fa 00 fa fa fa 00 fa fa fa 00 fa fa fa 00[fa]
  0x0c047fff9dc0: fa fa 00 fa fa fa 00 fa fa fa 00 fa fa fa 00 fa
  0x0c047fff9dd0: fa fa 00 fa fa fa 00 fa fa fa 00 fa fa fa 00 fa
  0x0c047fff9de0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c047fff9df0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c047fff9e00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
==32522==ABORTING
```

Благодаря написанным номерам строк я нашёл причину. Это следующая последовательность строк в `ReallocGraph`:
```
    bool** tempEdges = (bool**) calloc(sizeof(bool*), graph->numnodes);
    CHECK_ERR(tempEdges == NULL, "NOT ENOUGH MEMORY");
    for (int idx = 0; idx < graph->numnodes; idx++)
    {
        tempEdges[idx] = (bool*) calloc(sizeof(bool), graph->numnodes);
        CHECK_ERR(tempEdges[idx] == NULL, "NOT ENOUGH MEMORY");
    }

...

    graph->numnodes = graph->numnodes * 2;

...


    for (int idx1 = 0; idx1 < graph->numnodes; idx1++)
    {
        for (int idx2 = 0; idx2 < graph->numnodes; idx2++)
        {
            graph->edges[idx1][idx2] = tempEdges[idx1][idx2]; <<-- error
        }
    }
```
Как можно догадаться, после увеличения `graph->numnodes` вы попали на доступ за границы выделенного ранее массива `tempEdges`.
